version: '3.8'

services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/memearenabot
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
      - AI_OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - AI_STABILITY_API_KEY=${STABILITY_API_KEY:-}
      - MEME_STORAGE_PATH=/app/meme-storage
      - MEME_STORAGE_URL=http://localhost:8080/images/
    volumes:
      - meme-storage:/app/meme-storage
      - app-logs:/app/logs
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=memearenabot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres-data:
  meme-storage:
  app-logs:

networks:
  app-network:
    driver: bridge 